# Generated by Django 4.0.4 on 2022-06-26 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casys', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_receive',
            old_name='username_info_Receive',
            new_name='recipient_name',
        ),
    ]
