# Generated by Django 4.0.4 on 2022-07-02 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casys', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_receive',
            old_name='order_received',
            new_name='order_name',
        ),
    ]
