# Generated by Django 4.0.4 on 2022-06-26 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casys', '0002_rename_username_info_receive_product_receive_recipient_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='contact_no',
            new_name='contact_number',
        ),
        migrations.RenameField(
            model_name='shipment',
            old_name='order',
            new_name='order_name',
        ),
    ]
