# Generated by Django 4.0.4 on 2022-07-02 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casys', '0002_rename_order_received_product_receive_order_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='order_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casys.order'),
        ),
    ]
