# Generated by Django 4.0.4 on 2022-07-02 15:34

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('casys', '0003_alter_shipment_order_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='gcash_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
